version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "chalk"
    assignees:
      - "igwtcode"
    schedule:
      timezone: "Europe/Berlin"
      interval: "weekly"
      day: "saturday"
      time: "09:00"
