name: dev
on:
  workflow_dispatch:
  push:
    branches: ["igwtcode/issue[0-9]+", "dev-**", "dev/**"]
    paths-ignore: ["*.md", "*.png"]
jobs:
  build:
    permissions:
      contents: read
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        node-version:
          - "latest"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: ${{ matrix.node-version }}
      - name: setup cache
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: deps-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run build
